[project]
name = "nonebot-plugin-setu-now"
version = "0.6.4"
description = "另一个色图插件"
authors = [{ name = "kexue", email = "xana278@foxmail.com" }]
dependencies = [
    "httpx<1.0.0,>=0.18.0",
    "nonebot2>=2.0.0",
    "nonebot-adapter-onebot>=2.0.0",
    "pydantic>=1.5.0",
    "pillow>=8.0.0",
    "nonebot-plugin-tortoise-orm>=0.1.0",
    "nonebot-plugin-localstore>=0.5.0",
]
requires-python = ">=3.8,<4.0"
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["nonebot2"]


[project.urls]
homepage = "https://github.com/kexue-z/nonebot-plugin-setu-now"

[project.group.dev.dependencies]
isort = "^5.12.0"
flake8 = "^4.0.1"
black = "^22.3.0"

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.isort]
profile = "black"
